import QCECMeasurementBinding

#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T01_acceptance_requires_source_binding
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T02_acceptance_requires_instrument_calibration
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T03_acceptance_requires_null_observable_binding
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T04_acceptance_requires_unit_convention
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T05_acceptance_requires_uncertainty_binding
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T06_acceptance_requires_independent_reproduction
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T07_acceptance_requires_unit_time
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T08_acceptance_binds_measured_token
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T09_acceptance_yields_fixed_unit_time_reading
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T10_accepted_measurement_token_is_unique
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T11_same_calibration_forces_same_accepted_token
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T12_unbound_source_cannot_be_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T13_uncalibrated_instrument_cannot_be_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T14_unreproduced_receipt_cannot_be_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T15_mismatched_token_cannot_be_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T16_current_repository_candidate_is_not_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T17_complete_finite_si_like_receipt_is_accepted
#print axioms QIKVRT.V2.Physics.QCECMeasurementBinding.QCMB_T18_complete_finite_si_like_token_is_299792458
