import QCECausalAxisSelection

#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T01_canonical_time_axis_tracks_qce_seriality
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T02_canonical_tracking_axis_is_unique
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T03_canonical_evidence_is_resolvable
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T04_certificates_over_same_evidence_agree
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T05_certified_binding_carries_qce_serial_response
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T06_canonical_certificate_derives_time_dimension
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T07_ambiguous_length_axis_tracks_qce_seriality
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T08_ambiguous_time_axis_tracks_qce_seriality
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T09_length_time_evidence_is_ambiguous
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T10_ambiguous_evidence_fails_closed
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T11_absent_evidence_has_no_candidate
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T12_absent_evidence_fails_closed
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T13_same_qce_network_allows_resolved_and_ambiguous_evidence
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T14_evidence_replacement_preserves_qce_network
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T15_current_qce_cone_candidate_remains_open
#print axioms QIKVRT.V2.Physics.QCECausalAxisSelection.CAS_T16_current_qce_empirical_correspondence_remains_open
