options {
  directory "/tmp";
  pid-file "/run/named.pid";
  session-keyfile "/run/session.key";
  listen-on port 5353 { any; };
  listen-on-v6 { none; };
  recursion no;
  allow-query { any; };
  minimal-responses yes;
};

zone "qik-vrt.mesh" IN {
  type master;
  file "/opt/qikvrt/deploy/universal-terminal/db.qik-vrt.mesh";
  allow-update { none; };
};
