import QCENullCalibrationRatio

#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T01_normalized_and_si_share_causal_evidence
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T02_normalized_and_si_calibrations_are_distinct
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T03_representation_has_stable_null_boundary
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T04_representation_has_speed_dimension
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T05_reencoding_preserves_causal_evidence
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T06_reencoding_preserves_speed_dimension
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T07_normalized_calibration_has_unit_time
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T08_si_calibration_has_unit_time
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T09_normalized_c_token_is_one
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T10_si_like_c_token_is_299792458
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T11_fixed_reading_determines_c_token
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T12_fixed_reading_token_is_unique
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T13_normalized_to_si_conversion_factors
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T14_normalized_to_si_preserves_unit_time
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T15_time_preserving_conversion_keeps_unit_time
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T16_one_scalar_determines_c_token
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T17_same_causal_evidence_allows_distinct_c_tokens
#print axioms QIKVRT.V2.Physics.QCENullCalibrationRatio.QNCR_T18_unit_time_calibration_has_unique_c_token
