import QIKVRTFormalization.Hardware.AuthorityMirrorWitness

#print axioms QIKVRT.V2.HardwareWitness.T01_local_image_digest_integrity
#print axioms QIKVRT.V2.HardwareWitness.T02_witness_digest_integrity
#print axioms QIKVRT.V2.HardwareWitness.T03_prepared_pair_cross_binding
#print axioms QIKVRT.V2.HardwareWitness.T04_witness_requires_two_prepared_images
#print axioms QIKVRT.V2.HardwareWitness.T05_atomic_witness_is_commit_point
#print axioms QIKVRT.V2.HardwareWitness.T06_crash_before_witness_recovers_predecessor
#print axioms QIKVRT.V2.HardwareWitness.T07_crash_after_witness_recovers_successor
#print axioms QIKVRT.V2.HardwareWitness.T08_single_authority_survivor_reconstructs_mirror
#print axioms QIKVRT.V2.HardwareWitness.T09_single_mirror_survivor_reconstructs_authority
#print axioms QIKVRT.V2.HardwareWitness.T10_recovery_is_idempotent
#print axioms QIKVRT.V2.HardwareWitness.T11_repair_converges_to_equal_payload
#print axioms QIKVRT.V2.HardwareWitness.T12_monotone_witness_prevents_rollback
#print axioms QIKVRT.V2.HardwareWitness.T13_stale_staging_is_ignored_before_commit
#print axioms QIKVRT.V2.HardwareWitness.T14_mix_and_match_images_are_rejected
#print axioms QIKVRT.V2.HardwareWitness.T15_divergent_valid_duplex_without_witness_is_ambiguous
#print axioms QIKVRT.V2.HardwareWitness.T16_safe_witnessless_recovery_is_fail_closed
#print axioms QIKVRT.V2.HardwareWitness.T17_no_deterministic_duplex_selector_is_correct_for_both_hidden_histories
#print axioms QIKVRT.V2.HardwareWitness.T18_witness_resolves_a_unique_certified_epoch
#print axioms QIKVRT.V2.HardwareWitness.T19_effect_ack_requires_stable_witness_binding
#print axioms QIKVRT.V2.HardwareWitness.T20_effect_ack_is_idempotently_bound_to_witness
#print axioms QIKVRT.V2.HardwareWitness.T21_each_successful_transaction_advances_exactly_one_epoch
#print axioms QIKVRT.V2.HardwareWitness.T22_four_step_payload_sequences_remain_monotone
