import MeasurementDerivedDimensions

#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T01_derived_dimension_agrees_with_basis
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T02_basis_agreement_is_unique
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T03_nonderived_dimension_cannot_agree_with_all_basis_responses
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T04_calibration_action_has_unique_dimension
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T05_zero_calibration_has_zero_response
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T06_calibration_composition_is_additive
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T07_channel_dimension_is_basis_derived
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T08_equal_calibration_action_forces_equal_dimension
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T09_calibration_change_preserves_premetric_ontology
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T10_length_dimension_is_calibration_derived
#print axioms QIKVRT.V2.Physics.MeasurementDerivedDimensions.MDD_T11_time_dimension_is_calibration_derived
