import VRTCore_VirtualSphere

/-! Complete axiom audit for the 55 named H6 kernel theorems. -/

#print axioms QIKVRT.VRTCore.VirtualSphereH6.virtualClosure_ne_physicalClosure
#print axioms QIKVRT.VRTCore.VirtualSphereH6.virtualSeed_ne_physicalBigBang
#print axioms QIKVRT.VRTCore.VirtualSphereH6.state_ext_by_radius
#print axioms QIKVRT.VRTCore.VirtualSphereH6.shell_mem_iff
#print axioms QIKVRT.VRTCore.VirtualSphereH6.state_nonvacuous
#print axioms QIKVRT.VRTCore.VirtualSphereH6.state_noHole
#print axioms QIKVRT.VRTCore.VirtualSphereH6.outer_shell_absent
#print axioms QIKVRT.VRTCore.VirtualSphereH6.firstState_ne_seed
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_refines_stepSpec
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_strictly_grows
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_never_regresses
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_preserves_shells
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_shell_delta_exact
#print axioms QIKVRT.VRTCore.VirtualSphereH6.stepSpec_total_unique
#print axioms QIKVRT.VRTCore.VirtualSphereH6.stepSpec_deterministic
#print axioms QIKVRT.VRTCore.VirtualSphereH6.run_radius
#print axioms QIKVRT.VRTCore.VirtualSphereH6.run_reachable
#print axioms QIKVRT.VRTCore.VirtualSphereH6.seed_reachable
#print axioms QIKVRT.VRTCore.VirtualSphereH6.every_state_reachable
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_next
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_nonseed_has_predecessor
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_noHole
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_progress
#print axioms QIKVRT.VRTCore.VirtualSphereH6.run_strict_growth
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_unbounded
#print axioms QIKVRT.VRTCore.VirtualSphereH6.population_eq_radius_succ
#print axioms QIKVRT.VRTCore.VirtualSphereH6.next_population_exact
#print axioms QIKVRT.VRTCore.VirtualSphereH6.stateAt_injective
#print axioms QIKVRT.VRTCore.VirtualSphereH6.state_virtualInvariant
#print axioms QIKVRT.VRTCore.VirtualSphereH6.reachable_virtualInvariant
#print axioms QIKVRT.VRTCore.VirtualSphereH6.render_grammar
#print axioms QIKVRT.VRTCore.VirtualSphereH6.grammar_complete
#print axioms QIKVRT.VRTCore.VirtualSphereH6.parse_sound
#print axioms QIKVRT.VRTCore.VirtualSphereH6.parse_some_iff_grammar
#print axioms QIKVRT.VRTCore.VirtualSphereH6.parse_none_iff_not_wellFormed
#print axioms QIKVRT.VRTCore.VirtualSphereH6.render_wellFormed
#print axioms QIKVRT.VRTCore.VirtualSphereH6.parse_render_roundtrip
#print axioms QIKVRT.VRTCore.VirtualSphereH6.render_injective
#print axioms QIKVRT.VRTCore.VirtualSphereH6.grammar_unique
#print axioms QIKVRT.VRTCore.VirtualSphereH6.canonicalDocument_roundtrip_and_boundary
#print axioms QIKVRT.VRTCore.VirtualSphereH6.normalize_render
#print axioms QIKVRT.VRTCore.VirtualSphereH6.normalize_idempotent
#print axioms QIKVRT.VRTCore.VirtualSphereH6.deserialize_serialize
#print axioms QIKVRT.VRTCore.VirtualSphereH6.normalize_of_parse
#print axioms QIKVRT.VRTCore.VirtualSphereH6.normalize_preserves_document
#print axioms QIKVRT.VRTCore.VirtualSphereH6.effect_preserved
#print axioms QIKVRT.VRTCore.VirtualSphereH6.virtual_no_effect_escalation
#print axioms QIKVRT.VRTCore.VirtualSphereH6.no_external_authorization
#print axioms QIKVRT.VRTCore.VirtualSphereH6.semantic_binding_total_unique
#print axioms QIKVRT.VRTCore.VirtualSphereH6.canonicalDocument_exact_semanticModel
#print axioms QIKVRT.VRTCore.VirtualSphereH6.canonicalBits_exact_model
#print axioms QIKVRT.VRTCore.VirtualSphereH6.normalize_preserves_semantics
#print axioms QIKVRT.VRTCore.VirtualSphereH6.kernelClosureProjection_all_true
#print axioms QIKVRT.VRTCore.VirtualSphereH6.virtualCertificate_disjoint_physicalEvidence
#print axioms QIKVRT.VRTCore.VirtualSphereH6.h6_virtualSphere_noHole_complete
